[workspace]
members = ["1/day1_rs", "10/day10_rs", "11/day11_rs", "12/day12_rs", "13/day13_rs", "2/day2_rs", "3/day3_rs", "4/day4_rs", "5/day5_rs", "6/day6_rs", "7/day7_rs", "8/day8_rs", "9/day9_rs"]
resolver = "2"

[profile.release]
debug = true
