[package]
name = "day5_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tap = "1.0.1"
test-case = "3.3.1"
timed = "0.2.1"
