[package]
name = "day12_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
color-eyre = "0.6.3"
rayon = "1.10.0"
test-case = "3.3.1"
timed = "0.2.1"

[profile.release]
debug = true
